In [1]:
import pandas as pd
import sklearn
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import warnings
warnings.filterwarnings("ignore")

In [2]:
house_p = pd.read_csv('train.csv')
house_p

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
house_p.duplicated().sum()

0

In [4]:
house_p.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [5]:
house_p = house_p.drop(columns=["Alley", "PoolQC", "Fence", "MiscFeature"])
house_p

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [6]:
house_p["EnclosedPorch"].values

array([  0,   0,   0, ...,   0, 112,   0], dtype=int64)

In [7]:
house_p["3SsnPorch"].tolist()

[0,
 0,
 0,
 0,
 0,
 320,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 407,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 130,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 180,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 168,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 180,
 0,
 0,
 0,
 0,
 140,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 508,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 238,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 245,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 196,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 144,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 144,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 182,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 168,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 162,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 23,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 168,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [8]:
house_p["outdoorfeatures"]= house_p["EnclosedPorch"] + house_p["3SsnPorch"] + house_p["ScreenPorch"] + house_p["OpenPorchSF"] + house_p["PoolArea"]+ house_p["WoodDeckSF"]

In [9]:
house_p

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,outdoorfeatures
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,2,2008,WD,Normal,208500,61
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,5,2007,WD,Normal,181500,298
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,9,2008,WD,Normal,223500,42
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,0,2,2006,WD,Abnorml,140000,307
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,12,2008,WD,Normal,250000,276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,8,2007,WD,Normal,175000,40
1456,1457,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,2,2010,WD,Normal,210000,349
1457,1458,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,2500,5,2010,WD,Normal,266500,60
1458,1459,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,4,2010,WD,Normal,142125,478
1459,1460,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,6,2008,WD,Normal,147500,804

In [10]:
house_p = house_p.drop(columns=["3SsnPorch", "ScreenPorch", "EnclosedPorch", "OpenPorchSF", "PoolArea", "WoodDeckSF", "Id"])

In [11]:
house_p

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,GarageQual,GarageCond,PavedDrive,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,outdoorfeatures
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,TA,TA,Y,0,2,2008,WD,Normal,208500,61
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,TA,TA,Y,0,5,2007,WD,Normal,181500,298
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,TA,TA,Y,0,9,2008,WD,Normal,223500,42
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,TA,TA,Y,0,2,2006,WD,Abnorml,140000,307
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,TA,TA,Y,0,12,2008,WD,Normal,250000,276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,TA,TA,Y,0,8,2007,WD,Normal,175000,40
1456,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,TA,TA,Y,0,2,2010,WD,Normal,210000,349
1457,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,TA,TA,Y,2500,5,2010,WD,Normal,266500,60
1458,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,TA,TA,Y,0,4,2010,WD,Normal,142125,478
1459,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,TA,TA,Y,0,6,2008,WD,Normal,147500,804

In [12]:
house_p["PavedDrive"].tolist()

['Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'P',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'N',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'N',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'N',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'P',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'N',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'P',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'Y',
 'P',
 'Y',
 ...]

In [13]:
house_p.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice', 'outdoorfeatures'],
      dtype='object')

In [14]:
house_p[["GarageType", "GarageYrBlt", "GarageFinish", "GarageCars", "GarageArea", "GarageQual", "GarageCond"]]

,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond
0,Attchd,2003.0,RFn,2,548,TA,TA
1,Attchd,1976.0,RFn,2,460,TA,TA
2,Attchd,2001.0,RFn,2,608,TA,TA
3,Detchd,1998.0,Unf,3,642,TA,TA
4,Attchd,2000.0,RFn,3,836,TA,TA
...,...,...,...,...,...,...,...
1455,Attchd,1999.0,RFn,2,460,TA,TA
1456,Attchd,1978.0,Unf,2,500,TA,TA
1457,Attchd,1941.0,RFn,1,252,TA,TA
1458,Attchd,1950.0,Unf,1,240,TA,TA
1459,Attchd,1965.0,Fin,1,276,TA,TA

In [15]:
house_p["GarageQual"].tolist()

['TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'Gd',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 nan,
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Gd',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'Ex',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'Fa',
 'TA',
 'TA',
 'TA',
 'Po',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Ex',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'Gd',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'Po',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'Gd',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Po',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Gd',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 nan,
 'Gd',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 nan,
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Ex',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Gd',
 'Gd',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 ...]

In [16]:
house_p["GarageType"].tolist()

['Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'BuiltIn',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'CarPort',
 'Detchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Detchd',
 nan,
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 nan,
 'Attchd',
 'Attchd',
 'Detchd',
 'CarPort',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Detchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'BuiltIn',
 'Detchd',
 'Detchd',
 nan,
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'BuiltIn',
 'Attchd',
 'BuiltIn',
 'Detchd',
 nan,
 nan,
 'Detchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Basment',
 nan,
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Detchd',
 nan,
 'Attchd',
 'Attchd',
 'BuiltIn',
 'BuiltIn',
 'Basment',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 nan,
 'Attchd',
 nan,
 'Attchd',
 '2Types',
 'Attchd',
 'BuiltIn',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 '2Types',
 'Attchd',
 'Attchd',
 nan,
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Detchd',
 'BuiltIn',
 nan,
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 nan,
 'Detchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 nan,
 'Detchd',
 nan,
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 nan,
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 nan,
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 nan,
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 nan,
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 nan,
 'Detchd',
 'Detchd',
 'Attchd',
 nan,
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 nan,
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'CarPort',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Detchd',
 'BuiltIn',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Basment',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 nan,
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 nan,
 'Detchd',
 'Attchd',
 'BuiltIn',
 'Detchd',
 'BuiltIn',
 'Attchd',
 nan,
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'BuiltIn',
 'BuiltIn',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 nan,
 'Detchd',
 'Attchd',
 nan,
 'Attchd',
 'Detchd',
 'Detchd',
 'Detchd',
 'Detchd',
 'Attchd',
 nan,
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'BuiltIn',
 'Detchd',
 'Detchd',
 'Detchd',
 nan,
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Basment',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 nan,
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'CarPort',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 nan,
 'Attchd',
 'Detchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 nan,
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 nan,
 'Attchd',
 nan,
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Detchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'BuiltIn',
 'Detchd',
 'Attchd',
 'CarPort',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 nan,
 'Detchd',
 'Attchd',
 'Detchd',
 'BuiltIn',
 'Attchd',
 'BuiltIn',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'BuiltIn',
 'Detchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 nan,
 'Detchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'BuiltIn',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Basment',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 nan,
 nan,
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 nan,
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Basment',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 nan,
 nan,
 'BuiltIn',
 nan,
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 nan,
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'CarPort',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 '2Types',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Detchd',
 'Attchd',
 nan,
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 nan,
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 nan,
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'BuiltIn',
 'Detchd',
 'Attchd',
 'Detchd',
 nan,
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Detchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 nan,
 'Attchd',
 'Detchd',
 'BuiltIn',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Basment',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'BuiltIn',
 'Detchd',
 'Attchd',
 'Attchd',
 nan,
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Detchd',
 'Attchd',
 nan,
 'Detchd',
 'Basment',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Detchd',
 '2Types',
 'Detchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 nan,
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'BuiltIn',
 nan,
 'Attchd',
 'Basment',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 'Detchd',
 'Attchd',
 nan,
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Detchd',
 nan,
 'Attchd',
 'Detchd',
 'Attchd',
 'BuiltIn',
 'Attchd',
 'Detchd',
 'Attchd',
 nan,
 'Attchd',
 nan,
 'BuiltIn',
 'Attchd',
 'Attchd',
 'Detchd',
 'Detchd',
 nan,
 'Attchd',
 'Detchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 'Attchd',
 'Detchd',
 'Attchd',
 ...]

In [17]:
house_p["GarageYrBlt"].tolist()

[2003.0,
 1976.0,
 2001.0,
 1998.0,
 2000.0,
 1993.0,
 2004.0,
 1973.0,
 1931.0,
 1939.0,
 1965.0,
 2005.0,
 1962.0,
 2006.0,
 1960.0,
 1991.0,
 1970.0,
 1967.0,
 2004.0,
 1958.0,
 2005.0,
 1930.0,
 2002.0,
 1976.0,
 1968.0,
 2007.0,
 2005.0,
 2008.0,
 1957.0,
 1920.0,
 1920.0,
 1966.0,
 2007.0,
 1959.0,
 2005.0,
 2004.0,
 1995.0,
 1954.0,
 1953.0,
 nan,
 1965.0,
 1959.0,
 1983.0,
 1977.0,
 1959.0,
 2005.0,
 2003.0,
 2006.0,
 nan,
 1966.0,
 1997.0,
 1985.0,
 1963.0,
 1981.0,
 1962.0,
 1964.0,
 1999.0,
 2004.0,
 2006.0,
 1973.0,
 2006.0,
 1935.0,
 2006.0,
 1990.0,
 1998.0,
 2004.0,
 1970.0,
 2003.0,
 1945.0,
 1953.0,
 1973.0,
 1987.0,
 1998.0,
 1989.0,
 1915.0,
 1973.0,
 1956.0,
 1948.0,
 nan,
 1966.0,
 1968.0,
 1998.0,
 2007.0,
 1974.0,
 1995.0,
 1991.0,
 2005.0,
 2009.0,
 nan,
 nan,
 1950.0,
 1961.0,
 1921.0,
 1900.0,
 1997.0,
 1993.0,
 1999.0,
 1965.0,
 1920.0,
 nan,
 1977.0,
 1985.0,
 1979.0,
 2009.0,
 1951.0,
 2003.0,
 1954.0,
 1948.0,
 nan,
 1977.0,
 1954.0,
 2000.0,
 2007.0,
 1953.0,
 1945.0,
 1999.0,
 1962.0,
 2007.0,
 1990.0,
 2005.0,
 1969.0,
 1979.0,
 1958.0,
 1993.0,
 1979.0,
 nan,
 1977.0,
 nan,
 1966.0,
 1998.0,
 1966.0,
 2000.0,
 1974.0,
 2001.0,
 1968.0,
 1970.0,
 1967.0,
 1989.0,
 1999.0,
 1997.0,
 nan,
 2005.0,
 2000.0,
 1999.0,
 1963.0,
 2004.0,
 1931.0,
 2001.0,
 nan,
 1936.0,
 1975.0,
 2007.0,
 1971.0,
 1960.0,
 1923.0,
 nan,
 1950.0,
 2009.0,
 2004.0,
 2006.0,
 1984.0,
 2003.0,
 2005.0,
 nan,
 1926.0,
 nan,
 1955.0,
 2007.0,
 2004.0,
 1981.0,
 1991.0,
 1960.0,
 1987.0,
 1961.0,
 1986.0,
 1950.0,
 1988.0,
 1958.0,
 2009.0,
 1935.0,
 2000.0,
 1920.0,
 1957.0,
 2003.0,
 1986.0,
 1993.0,
 1990.0,
 1916.0,
 1979.0,
 2001.0,
 1932.0,
 1972.0,
 1999.0,
 2004.0,
 1989.0,
 1976.0,
 2007.0,
 1918.0,
 nan,
 2004.0,
 2003.0,
 1980.0,
 1924.0,
 2004.0,
 1948.0,
 1990.0,
 1962.0,
 1960.0,
 1988.0,
 1964.0,
 nan,
 2009.0,
 2009.0,
 1996.0,
 1977.0,
 1957.0,
 2004.0,
 1940.0,
 1939.0,
 2005.0,
 2006.0,
 2002.0,
 1975.0,
 1989.0,
 2003.0,
 1991.0,
 1995.0,
 1987.0,
 1974.0,
 2005.0,
 1959.0,
 1995.0,
 1972.0,
 1976.0,
 2002.0,
 1971.0,
 2004.0,
 1993.0,
 2007.0,
 1949.0,
 2008.0,
 nan,
 1940.0,
 1980.0,
 1994.0,
 1988.0,
 1910.0,
 1954.0,
 2003.0,
 1958.0,
 nan,
 2006.0,
 2004.0,
 1964.0,
 1957.0,
 1999.0,
 2003.0,
 2006.0,
 2001.0,
 1956.0,
 1991.0,
 2007.0,
 1978.0,
 1974.0,
 1965.0,
 1981.0,
 1997.0,
 1939.0,
 1966.0,
 1987.0,
 2006.0,
 1954.0,
 1999.0,
 1958.0,
 1982.0,
 1978.0,
 2003.0,
 1951.0,
 2007.0,
 1977.0,
 1989.0,
 2006.0,
 2008.0,
 2008.0,
 1992.0,
 2006.0,
 1962.0,
 nan,
 1970.0,
 2003.0,
 2006.0,
 nan,
 1949.0,
 1977.0,
 1953.0,
 1984.0,
 1950.0,
 1997.0,
 1968.0,
 1950.0,
 1953.0,
 1998.0,
 2001.0,
 1975.0,
 2003.0,
 2004.0,
 1990.0,
 nan,
 1961.0,
 2003.0,
 1993.0,
 1948.0,
 1939.0,
 1965.0,
 1925.0,
 2004.0,
 1983.0,
 2006.0,
 1993.0,
 1980.0,
 2006.0,
 2004.0,
 1987.0,
 1955.0,
 1961.0,
 1941.0,
 1993.0,
 1960.0,
 1930.0,
 1920.0,
 2002.0,
 1958.0,
 2003.0,
 2004.0,
 1998.0,
 1965.0,
 2005.0,
 2002.0,
 1984.0,
 1958.0,
 2002.0,
 1950.0,
 1949.0,
 2005.0,
 1976.0,
 1939.0,
 1960.0,
 1960.0,
 2003.0,
 2006.0,
 2007.0,
 1986.0,
 1941.0,
 2005.0,
 1940.0,
 1995.0,
 1992.0,
 1976.0,
 1958.0,
 1998.0,
 1978.0,
 1940.0,
 2003.0,
 1972.0,
 1976.0,
 1964.0,
 1963.0,
 1962.0,
 1954.0,
 1997.0,
 2000.0,
 1991.0,
 1984.0,
 1953.0,
 2003.0,
 nan,
 1998.0,
 2004.0,
 2010.0,
 2000.0,
 1924.0,
 2006.0,
 2006.0,
 1950.0,
 1992.0,
 2004.0,
 nan,
 1977.0,
 1999.0,
 2008.0,
 1978.0,
 2001.0,
 1959.0,
 nan,
 1940.0,
 1956.0,
 1985.0,
 1962.0,
 1920.0,
 2007.0,
 1996.0,
 2005.0,
 1940.0,
 1998.0,
 1995.0,
 1993.0,
 1936.0,
 1960.0,
 2006.0,
 2008.0,
 1958.0,
 1955.0,
 2009.0,
 1927.0,
 1993.0,
 2007.0,
 1978.0,
 1918.0,
 1940.0,
 1968.0,
 1997.0,
 1977.0,
 1954.0,
 1998.0,
 1956.0,
 1947.0,
 1989.0,
 1964.0,
 2007.0,
 1988.0,
 1971.0,
 nan,
 1971.0,
 1997.0,
 nan,
 1996.0,
 1990.0,
 1926.0,
 1990.0,
 2005.0,
 2008.0,
 nan,
 1930.0,
 2007.0,
 1994.0,
 1956.0,
 1966.0,
 1998.0,
 1937.0,
 1981.0,
 1932.0,
 1975.0,
 1996.0,
 2008.0,
 1976.0,
 1973.0,
 1916.0,
 1954.0,
 1925.0,
 1950.0,
 2009.0,
 1971.0,
 1965.0,
 1939.0,
 nan,
 2004.0,
 1970.0,
 1942.0,
 2006.0,
 1993.0,
 1985.0,
 1977.0,
 2005.0,
 2006.0,
 2000.0,
 1996.0,
 1997.0,
 2006.0,
 2007.0,
 1995.0,
 2004.0,
 2003.0,
 1915.0,
 1998.0,
 1963.0,
 1950.0,
 1965.0,
 1971.0,
 1970.0,
 1970.0,
 1976.0,
 1941.0,
 2006.0,
 1964.0,
 1938.0,
 nan,
 1992.0,
 1925.0,
 1967.0,
 1958.0,
 1973.0,
 2005.0,
 1965.0,
 1959.0,
 1974.0,
 1952.0,
 1993.0,
 2009.0,
 1928.0,
 1959.0,
 1951.0,
 2005.0,
 1964.0,
 1983.0,
 1926.0,
 2009.0,
 1972.0,
 1996.0,
 1998.0,
 1926.0,
 nan,
 1957.0,
 1950.0,
 2007.0,
 1996.0,
 2005.0,
 1956.0,
 2008.0,
 nan,
 1975.0,
 1988.0,
 1920.0,
 1967.0,
 nan,
 2004.0,
 nan,
 1998.0,
 1980.0,
 1968.0,
 2001.0,
 2006.0,
 2000.0,
 1998.0,
 1998.0,
 2006.0,
 1988.0,
 1950.0,
 1987.0,
 1963.0,
 2003.0,
 1977.0,
 1957.0,
 2006.0,
 2002.0,
 2003.0,
 1922.0,
 1957.0,
 1994.0,
 1996.0,
 2003.0,
 1957.0,
 1975.0,
 nan,
 1955.0,
 1992.0,
 1920.0,
 2005.0,
 2004.0,
 1983.0,
 1979.0,
 1987.0,
 1959.0,
 2009.0,
 2000.0,
 1971.0,
 1947.0,
 1928.0,
 1966.0,
 2007.0,
 1954.0,
 1960.0,
 2009.0,
 nan,
 1988.0,
 1935.0,
 2005.0,
 1961.0,
 1996.0,
 1968.0,
 1988.0,
 2004.0,
 2008.0,
 1985.0,
 2003.0,
 1981.0,
 2005.0,
 1930.0,
 2006.0,
 1977.0,
 1980.0,
 2003.0,
 1979.0,
 1992.0,
 2004.0,
 2002.0,
 1965.0,
 2000.0,
 1948.0,
 1934.0,
 1961.0,
 2000.0,
 1978.0,
 2001.0,
 nan,
 nan,
 1963.0,
 2002.0,
 1962.0,
 2007.0,
 2003.0,
 nan,
 1974.0,
 1986.0,
 2000.0,
 1972.0,
 1962.0,
 1960.0,
 1955.0,
 1969.0,
 1964.0,
 1937.0,
 2006.0,
 1977.0,
 1954.0,
 1980.0,
 nan,
 nan,
 1954.0,
 nan,
 2006.0,
 2003.0,
 2001.0,
 1972.0,
 1969.0,
 2009.0,
 1979.0,
 1950.0,
 1953.0,
 1966.0,
 nan,
 2007.0,
 1940.0,
 1996.0,
 1906.0,
 1995.0,
 1971.0,
 1959.0,
 1931.0,
 1948.0,
 1968.0,
 1976.0,
 1994.0,
 1968.0,
 1974.0,
 2005.0,
 2000.0,
 1965.0,
 1994.0,
 1999.0,
 1922.0,
 2005.0,
 1930.0,
 1977.0,
 1957.0,
 1965.0,
 1978.0,
 1920.0,
 1924.0,
 2008.0,
 1963.0,
 1980.0,
 1968.0,
 1996.0,
 2002.0,
 1998.0,
 1984.0,
 2007.0,
 2004.0,
 2007.0,
 2005.0,
 2004.0,
 1994.0,
 1989.0,
 1968.0,
 1995.0,
 1987.0,
 1921.0,
 1952.0,
 1973.0,
 2004.0,
 2002.0,
 1969.0,
 2006.0,
 1999.0,
 2004.0,
 nan,
 1971.0,
 2006.0,
 2007.0,
 1966.0,
 nan,
 1964.0,
 1988.0,
 1970.0,
 1976.0,
 1974.0,
 1996.0,
 1973.0,
 1993.0,
 1969.0,
 1985.0,
 2004.0,
 1994.0,
 1958.0,
 2007.0,
 1989.0,
 1988.0,
 2007.0,
 1968.0,
 1962.0,
 1995.0,
 2003.0,
 1998.0,
 1961.0,
 1968.0,
 1914.0,
 1949.0,
 2005.0,
 nan,
 2004.0,
 1910.0,
 1962.0,
 2000.0,
 1997.0,
 1993.0,
 1994.0,
 2000.0,
 1950.0,
 1996.0,
 1945.0,
 nan,
 2003.0,
 1997.0,
 2005.0,
 1969.0,
 1999.0,
 2007.0,
 1978.0,
 1999.0,
 1995.0,
 2008.0,
 1965.0,
 2009.0,
 1999.0,
 1995.0,
 2008.0,
 1988.0,
 1989.0,
 2004.0,
 2003.0,
 1983.0,
 1951.0,
 1976.0,
 1958.0,
 2006.0,
 1998.0,
 2005.0,
 1974.0,
 1977.0,
 1977.0,
 1995.0,
 1992.0,
 2001.0,
 1978.0,
 nan,
 1967.0,
 1961.0,
 2004.0,
 1954.0,
 1966.0,
 2005.0,
 1976.0,
 1997.0,
 2007.0,
 1994.0,
 1980.0,
 1977.0,
 1953.0,
 2009.0,
 1939.0,
 1997.0,
 1957.0,
 2005.0,
 2009.0,
 1954.0,
 2008.0,
 1967.0,
 1923.0,
 1966.0,
 1910.0,
 1974.0,
 2004.0,
 1952.0,
 1958.0,
 1955.0,
 1998.0,
 1954.0,
 2002.0,
 1971.0,
 2010.0,
 2003.0,
 1974.0,
 2003.0,
 1940.0,
 2006.0,
 2007.0,
 nan,
 2001.0,
 1967.0,
 2005.0,
 1957.0,
 2005.0,
 2003.0,
 1964.0,
 1961.0,
 1996.0,
 1948.0,
 1973.0,
 1999.0,
 1946.0,
 1934.0,
 1983.0,
 1966.0,
 nan,
 1949.0,
 1975.0,
 1993.0,
 1972.0,
 1908.0,
 1976.0,
 2003.0,
 2003.0,
 1941.0,
 1964.0,
 1955.0,
 1962.0,
 1981.0,
 1994.0,
 1976.0,
 1968.0,
 1925.0,
 1965.0,
 1986.0,
 1959.0,
 2008.0,
 1973.0,
 2007.0,
 1961.0,
 1979.0,
 1993.0,
 1962.0,
 1998.0,
 1953.0,
 1949.0,
 1941.0,
 2007.0,
 1963.0,
 2004.0,
 1987.0,
 1978.0,
 2005.0,
 1990.0,
 1993.0,
 1997.0,
 1967.0,
 1999.0,
 2005.0,
 1955.0,
 1970.0,
 1953.0,
 2003.0,
 1978.0,
 1963.0,
 1954.0,
 1979.0,
 1963.0,
 1936.0,
 1979.0,
 2009.0,
 1961.0,
 1979.0,
 1968.0,
 2003.0,
 2006.0,
 1967.0,
 1954.0,
 2006.0,
 1936.0,
 1983.0,
 2005.0,
 1960.0,
 1978.0,
 1925.0,
 1949.0,
 2009.0,
 1970.0,
 1958.0,
 1956.0,
 1991.0,
 1990.0,
 1994.0,
 nan,
 2005.0,
 1993.0,
 1980.0,
 1977.0,
 2003.0,
 1968.0,
 2001.0,
 1997.0,
 2007.0,
 1965.0,
 2006.0,
 2004.0,
 1960.0,
 1953.0,
 2003.0,
 2005.0,
 2006.0,
 1940.0,
 1976.0,
 1999.0,
 nan,
 1967.0,
 1958.0,
 1963.0,
 1959.0,
 2002.0,
 2002.0,
 1972.0,
 1980.0,
 1979.0,
 1974.0,
 1969.0,
 nan,
 1946.0,
 1980.0,
 1977.0,
 2003.0,
 1999.0,
 nan,
 1977.0,
 1976.0,
 2007.0,
 2002.0,
 2005.0,
 1940.0,
 1955.0,
 nan,
 1958.0,
 nan,
 2003.0,
 1979.0,
 2007.0,
 1997.0,
 2000.0,
 nan,
 2007.0,
 1999.0,
 1963.0,
 1961.0,
 1998.0,
 2007.0,
 2002.0,
 1977.0,
 1950.0,
 1950.0,
 2010.0,
 1976.0,
 2006.0,
 1997.0,
 1925.0,
 1964.0,
 2005.0,
 2008.0,
 1946.0,
 1961.0,
 1970.0,
 1922.0,
 2006.0,
 ...]

In [18]:
house_p["GarageFinish"].tolist()

['RFn',
 'RFn',
 'RFn',
 'Unf',
 'RFn',
 'Unf',
 'RFn',
 'RFn',
 'Unf',
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'RFn',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'RFn',
 'Fin',
 'Fin',
 'Unf',
 'Fin',
 'Unf',
 nan,
 'RFn',
 'RFn',
 'RFn',
 'Unf',
 'RFn',
 'RFn',
 'RFn',
 'RFn',
 nan,
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 'Fin',
 'RFn',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'RFn',
 'RFn',
 'RFn',
 'RFn',
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 nan,
 'Unf',
 'Fin',
 'Fin',
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'Fin',
 'RFn',
 nan,
 nan,
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'Fin',
 'RFn',
 'Fin',
 'Unf',
 nan,
 'RFn',
 'Fin',
 'Unf',
 'RFn',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 nan,
 'RFn',
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 nan,
 'RFn',
 nan,
 'RFn',
 'RFn',
 'Fin',
 'RFn',
 'Unf',
 'Fin',
 'RFn',
 'Unf',
 'RFn',
 'Unf',
 'Fin',
 'RFn',
 nan,
 'Fin',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 nan,
 'Unf',
 'Unf',
 'RFn',
 'RFn',
 'RFn',
 'Unf',
 nan,
 'Unf',
 'Fin',
 'RFn',
 'RFn',
 'Unf',
 'Fin',
 'RFn',
 nan,
 'Unf',
 nan,
 'Fin',
 'Fin',
 'Fin',
 'RFn',
 'Unf',
 'Fin',
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 nan,
 'Fin',
 'RFn',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'RFn',
 'RFn',
 'RFn',
 'Fin',
 'RFn',
 nan,
 'RFn',
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'RFn',
 'RFn',
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'Fin',
 'RFn',
 'Fin',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 'RFn',
 'Fin',
 'Unf',
 'RFn',
 nan,
 'Unf',
 'RFn',
 'RFn',
 'Fin',
 'Unf',
 'Unf',
 'RFn',
 'Fin',
 nan,
 'Fin',
 'RFn',
 'RFn',
 'RFn',
 'Fin',
 'RFn',
 'RFn',
 'RFn',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 'Fin',
 'RFn',
 'RFn',
 'Unf',
 'Fin',
 'RFn',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'Fin',
 'Fin',
 'Fin',
 'Fin',
 'RFn',
 'Fin',
 'RFn',
 'RFn',
 'RFn',
 nan,
 'Unf',
 'Unf',
 'RFn',
 nan,
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'RFn',
 'Unf',
 'Unf',
 'Fin',
 'RFn',
 nan,
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'Fin',
 'RFn',
 'RFn',
 'RFn',
 'Unf',
 'RFn',
 'Fin',
 'Fin',
 'Unf',
 'Fin',
 'Unf',
 'Fin',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'RFn',
 'RFn',
 'Fin',
 'Fin',
 'Fin',
 'RFn',
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'RFn',
 'Fin',
 'RFn',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'RFn',
 'Fin',
 'Unf',
 'RFn',
 'RFn',
 'Unf',
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 'RFn',
 'Fin',
 'Fin',
 'RFn',
 'Fin',
 'Unf',
 'Unf',
 'Fin',
 nan,
 'Unf',
 'RFn',
 'Fin',
 'Fin',
 'Unf',
 'RFn',
 'RFn',
 'Unf',
 'Fin',
 'Fin',
 nan,
 'Unf',
 'RFn',
 'Fin',
 'Unf',
 'Fin',
 'RFn',
 nan,
 'Unf',
 'Unf',
 'RFn',
 'RFn',
 'Unf',
 'Fin',
 'Fin',
 'Fin',
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'Fin',
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'Fin',
 'RFn',
 'Fin',
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 nan,
 'Unf',
 'Fin',
 nan,
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 nan,
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'Fin',
 'RFn',
 'Unf',
 'Unf',
 nan,
 'Fin',
 'Unf',
 'Unf',
 'RFn',
 'RFn',
 'RFn',
 'RFn',
 'RFn',
 'RFn',
 'RFn',
 'Unf',
 'Fin',
 'Fin',
 'RFn',
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 nan,
 'RFn',
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'RFn',
 'Fin',
 'Unf',
 'RFn',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'RFn',
 'RFn',
 'RFn',
 'Unf',
 nan,
 'Unf',
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 'Fin',
 nan,
 'RFn',
 'RFn',
 'Fin',
 'Unf',
 nan,
 'Fin',
 nan,
 'Fin',
 'Unf',
 'Unf',
 'RFn',
 'Fin',
 'Fin',
 'Fin',
 'Fin',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'Fin',
 'RFn',
 'Fin',
 'RFn',
 'Fin',
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 nan,
 'Fin',
 'RFn',
 'Unf',
 'Fin',
 'RFn',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 nan,
 'Unf',
 'Unf',
 'RFn',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'RFn',
 'Fin',
 'Fin',
 'Unf',
 'Fin',
 'Unf',
 'Fin',
 'Fin',
 'Fin',
 'Fin',
 'Unf',
 'Fin',
 'RFn',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 nan,
 nan,
 'RFn',
 'Fin',
 'Unf',
 'Unf',
 'Fin',
 nan,
 'RFn',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'RFn',
 'RFn',
 'Unf',
 'RFn',
 'Unf',
 'RFn',
 'Fin',
 'Unf',
 'Unf',
 nan,
 nan,
 'Unf',
 nan,
 'Fin',
 'RFn',
 'Fin',
 'Fin',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 nan,
 'RFn',
 'Unf',
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 'RFn',
 'Unf',
 'Fin',
 'RFn',
 'RFn',
 'RFn',
 'RFn',
 'Fin',
 'RFn',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 'Fin',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'Fin',
 'Fin',
 'Fin',
 'Fin',
 'Unf',
 'RFn',
 'RFn',
 'RFn',
 'Fin',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'Fin',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 nan,
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 nan,
 'RFn',
 'Fin',
 'Unf',
 'RFn',
 'RFn',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'RFn',
 'RFn',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'Fin',
 'RFn',
 'Unf',
 'Unf',
 'RFn',
 'Fin',
 'Fin',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 nan,
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'RFn',
 'Fin',
 'Fin',
 'Unf',
 'Fin',
 'Unf',
 nan,
 'Fin',
 'RFn',
 'RFn',
 'RFn',
 'Unf',
 'RFn',
 'Fin',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'Fin',
 'Fin',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'RFn',
 'RFn',
 'Fin',
 nan,
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'Fin',
 'Fin',
 'RFn',
 'Unf',
 'Fin',
 'Fin',
 'Unf',
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 'Unf',
 'Fin',
 'RFn',
 'Unf',
 'RFn',
 'Fin',
 'RFn',
 'RFn',
 'Unf',
 'RFn',
 'Fin',
 'Unf',
 'RFn',
 'Unf',
 'RFn',
 'RFn',
 'RFn',
 'Unf',
 'RFn',
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 'Fin',
 nan,
 'RFn',
 'Fin',
 'RFn',
 'RFn',
 'RFn',
 'RFn',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 nan,
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'Fin',
 'Fin',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'Fin',
 'RFn',
 'RFn',
 'Unf',
 'RFn',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'RFn',
 'RFn',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'RFn',
 'Unf',
 'RFn',
 'RFn',
 'Fin',
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'Unf',
 'RFn',
 'RFn',
 'Unf',
 'RFn',
 nan,
 'Fin',
 'RFn',
 'Unf',
 'RFn',
 'Fin',
 'RFn',
 'RFn',
 'Fin',
 'Fin',
 'Unf',
 'Fin',
 'RFn',
 'RFn',
 'Unf',
 'RFn',
 'RFn',
 'RFn',
 'Unf',
 'Unf',
 'RFn',
 nan,
 'Unf',
 'RFn',
 'Unf',
 'RFn',
 'Fin',
 'RFn',
 'RFn',
 'RFn',
 'Unf',
 'Fin',
 'RFn',
 nan,
 'Unf',
 'Fin',
 'Fin',
 'RFn',
 'Unf',
 nan,
 'Fin',
 'Unf',
 'Fin',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 nan,
 'RFn',
 nan,
 'RFn',
 'Unf',
 'Fin',
 'Unf',
 'Unf',
 nan,
 'Fin',
 'Unf',
 'Unf',
 'RFn',
 'Fin',
 'Fin',
 'Unf',
 'Unf',
 'Unf',
 'Unf',
 'Fin',
 'Fin',
 'RFn',
 'Fin',
 'Unf',
 'RFn',
 'RFn',
 'Fin',
 'Unf',
 'Unf',
 'RFn',
 'Unf',
 'RFn',
 ...]

In [19]:
house_p["GarageCars"].tolist()

[2,
 2,
 2,
 3,
 3,
 2,
 2,
 2,
 2,
 1,
 1,
 3,
 1,
 3,
 1,
 2,
 2,
 2,
 2,
 1,
 3,
 1,
 2,
 2,
 1,
 3,
 2,
 3,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 3,
 2,
 2,
 1,
 0,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 3,
 1,
 2,
 1,
 2,
 2,
 2,
 3,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 0,
 2,
 2,
 2,
 3,
 1,
 2,
 1,
 1,
 0,
 2,
 1,
 2,
 3,
 2,
 1,
 2,
 1,
 2,
 3,
 2,
 2,
 1,
 1,
 2,
 2,
 0,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 3,
 3,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 0,
 1,
 2,
 3,
 2,
 2,
 1,
 0,
 2,
 3,
 2,
 2,
 2,
 3,
 2,
 0,
 1,
 0,
 1,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 1,
 1,
 2,
 2,
 3,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 3,
 2,
 0,
 3,
 2,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 0,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 1,
 3,
 1,
 1,
 2,
 1,
 3,
 1,
 1,
 2,
 1,
 2,
 2,
 3,
 1,
 2,
 0,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 0,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 2,
 3,
 1,
 1,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 0,
 1,
 1,
 2,
 0,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 3,
 2,
 3,
 3,
 3,
 0,
 2,
 3,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 2,
 3,
 3,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 3,
 2,
 2,
 2,
 3,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 3,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 0,
 2,
 2,
 3,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 0,
 1,
 2,
 3,
 1,
 2,
 1,
 0,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 3,
 3,
 1,
 2,
 2,
 2,
 3,
 2,
 2,
 3,
 1,
 1,
 4,
 2,
 2,
 3,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 0,
 2,
 2,
 0,
 2,
 2,
 1,
 1,
 2,
 3,
 0,
 2,
 3,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 0,
 2,
 2,
 1,
 3,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 3,
 3,
 2,
 3,
 3,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 3,
 2,
 3,
 2,
 1,
 0,
 1,
 2,
 3,
 3,
 2,
 1,
 3,
 0,
 2,
 2,
 2,
 1,
 0,
 2,
 0,
 2,
 2,
 1,
 2,
 3,
 3,
 2,
 1,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 1,
 3,
 2,
 3,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 0,
 2,
 2,
 1,
 3,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 3,
 0,
 2,
 1,
 3,
 1,
 2,
 1,
 1,
 2,
 3,
 2,
 2,
 1,
 3,
 1,
 3,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 3,
 2,
 2,
 0,
 0,
 2,
 2,
 2,
 3,
 3,
 0,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 0,
 0,
 1,
 0,
 3,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 0,
 2,
 1,
 2,
 1,
 3,
 1,
 1,
 1,
 1,
 2,
 2,
 3,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 3,
 1,
 3,
 2,
 1,
 1,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 3,
 2,
 3,
 2,
 2,
 0,
 2,
 2,
 2,
 1,
 0,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 1,
 2,
 2,
 2,
 1,
 3,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 3,
 0,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 4,
 2,
 1,
 0,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 3,
 1,
 2,
 2,
 3,
 2,
 2,
 2,
 1,
 2,
 3,
 2,
 2,
 2,
 1,
 3,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 3,
 1,
 2,
 2,
 2,
 3,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 3,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 3,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 0,
 3,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 3,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 3,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 3,
 1,
 1,
 1,
 2,
 3,
 1,
 1,
 3,
 1,
 2,
 2,
 2,
 1,
 1,
 3,
 2,
 1,
 1,
 1,
 3,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 3,
 1,
 3,
 2,
 2,
 2,
 2,
 2,
 3,
 1,
 2,
 2,
 0,
 2,
 2,
 2,
 1,
 3,
 2,
 2,
 2,
 1,
 1,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 0,
 1,
 0,
 2,
 1,
 2,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 1,
 1,
 3,
 2,
 2,
 3,
 2,
 2,
 2,
 3,
 1,
 1,
 2,
 1,
 2,
 ...]

In [20]:
house_p["GarageArea"].tolist()

[548,
 460,
 608,
 642,
 836,
 480,
 636,
 484,
 468,
 205,
 384,
 736,
 352,
 840,
 352,
 576,
 480,
 516,
 576,
 294,
 853,
 280,
 534,
 572,
 270,
 890,
 576,
 772,
 319,
 240,
 250,
 271,
 484,
 447,
 556,
 691,
 672,
 498,
 246,
 0,
 440,
 308,
 504,
 308,
 300,
 576,
 670,
 826,
 0,
 386,
 388,
 528,
 516,
 894,
 572,
 576,
 480,
 565,
 641,
 352,
 576,
 288,
 484,
 480,
 645,
 852,
 576,
 558,
 220,
 667,
 516,
 360,
 427,
 490,
 379,
 297,
 283,
 240,
 0,
 440,
 509,
 405,
 758,
 461,
 400,
 462,
 400,
 528,
 0,
 0,
 420,
 480,
 432,
 506,
 684,
 420,
 472,
 432,
 366,
 0,
 480,
 476,
 410,
 740,
 240,
 648,
 273,
 250,
 0,
 546,
 325,
 400,
 792,
 450,
 180,
 440,
 288,
 430,
 594,
 390,
 540,
 264,
 288,
 530,
 435,
 0,
 440,
 0,
 453,
 750,
 487,
 390,
 624,
 471,
 440,
 530,
 318,
 766,
 660,
 470,
 0,
 660,
 720,
 577,
 504,
 380,
 180,
 434,
 0,
 240,
 440,
 866,
 495,
 564,
 312,
 0,
 625,
 680,
 678,
 576,
 516,
 726,
 532,
 0,
 216,
 0,
 303,
 789,
 440,
 511,
 660,
 528,
 504,
 504,
 616,
 576,
 521,
 451,
 1166,
 480,
 440,
 216,
 252,
 484,
 576,
 840,
 497,
 180,
 528,
 682,
 440,
 484,
 666,
 380,
 352,
 440,
 786,
 795,
 0,
 856,
 440,
 473,
 398,
 420,
 240,
 500,
 349,
 312,
 454,
 504,
 0,
 460,
 644,
 576,
 299,
 447,
 484,
 210,
 431,
 438,
 675,
 390,
 434,
 576,
 968,
 280,
 721,
 280,
 336,
 430,
 312,
 810,
 288,
 308,
 440,
 264,
 494,
 457,
 818,
 220,
 750,
 0,
 352,
 288,
 463,
 604,
 440,
 451,
 500,
 389,
 0,
 538,
 520,
 309,
 294,
 429,
 673,
 660,
 564,
 308,
 884,
 868,
 492,
 484,
 504,
 576,
 413,
 240,
 924,
 504,
 1053,
 439,
 671,
 338,
 264,
 672,
 573,
 400,
 732,
 505,
 575,
 572,
 626,
 898,
 529,
 528,
 440,
 0,
 280,
 384,
 685,
 0,
 281,
 539,
 418,
 588,
 282,
 576,
 539,
 300,
 375,
 683,
 843,
 552,
 870,
 888,
 746,
 0,
 539,
 708,
 420,
 240,
 410,
 513,
 546,
 432,
 484,
 1025,
 656,
 588,
 840,
 872,
 576,
 220,
 564,
 360,
 473,
 292,
 441,
 189,
 352,
 308,
 880,
 484,
 472,
 529,
 676,
 532,
 440,
 297,
 431,
 294,
 400,
 564,
 336,
 312,
 301,
 498,
 474,
 706,
 617,
 445,
 200,
 484,
 240,
 521,
 400,
 528,
 288,
 592,
 470,
 240,
 672,
 264,
 566,
 468,
 514,
 296,
 244,
 576,
 460,
 680,
 264,
 270,
 434,
 0,
 576,
 610,
 834,
 463,
 308,
 572,
 639,
 360,
 501,
 430,
 0,
 352,
 577,
 846,
 384,
 560,
 294,
 0,
 240,
 596,
 600,
 264,
 338,
 438,
 500,
 400,
 240,
 420,
 373,
 490,
 240,
 308,
 947,
 836,
 350,
 572,
 484,
 360,
 678,
 396,
 440,
 864,
 240,
 304,
 784,
 529,
 520,
 696,
 297,
 240,
 569,
 352,
 628,
 576,
 264,
 0,
 440,
 470,
 0,
 550,
 440,
 180,
 352,
 528,
 672,
 0,
 360,
 648,
 493,
 480,
 578,
 431,
 198,
 308,
 270,
 576,
 422,
 676,
 560,
 528,
 513,
 529,
 228,
 352,
 552,
 576,
 360,
 240,
 0,
 398,
 526,
 312,
 866,
 506,
 528,
 534,
 525,
 908,
 499,
 624,
 508,
 694,
 826,
 672,
 772,
 874,
 164,
 402,
 264,
 264,
 515,
 487,
 520,
 286,
 336,
 240,
 429,
 308,
 273,
 0,
 546,
 240,
 288,
 297,
 264,
 603,
 461,
 484,
 440,
 400,
 471,
 676,
 360,
 270,
 288,
 474,
 624,
 484,
 200,
 900,
 583,
 889,
 546,
 282,
 0,
 336,
 420,
 884,
 834,
 453,
 252,
 858,
 0,
 484,
 600,
 502,
 392,
 0,
 403,
 0,
 527,
 576,
 336,
 670,
 765,
 648,
 583,
 367,
 426,
 786,
 440,
 624,
 720,
 615,
 440,
 288,
 908,
 520,
 871,
 280,
 299,
 570,
 406,
 420,
 528,
 418,
 0,
 396,
 590,
 216,
 656,
 532,
 612,
 600,
 576,
 288,
 650,
 400,
 288,
 336,
 216,
 564,
 540,
 352,
 572,
 1390,
 0,
 880,
 240,
 880,
 275,
 528,
 452,
 308,
 520,
 842,
 816,
 420,
 280,
 758,
 216,
 648,
 621,
 452,
 736,
 544,
 506,
 480,
 530,
 486,
 576,
 230,
 380,
 261,
 736,
 564,
 531,
 0,
 0,
 480,
 393,
 528,
 774,
 749,
 0,
 624,
 484,
 440,
 484,
 440,
 286,
 364,
 504,
 520,
 240,
 627,
 544,
 260,
 576,
 0,
 0,
 256,
 0,
 648,
 588,
 650,
 538,
 462,
 478,
 576,
 420,
 495,
 442,
 0,
 562,
 296,
 512,
 216,
 839,
 264,
 312,
 270,
 330,
 480,
 550,
 711,
 576,
 588,
 1134,
 504,
 596,
 575,
 576,
 252,
 540,
 300,
 546,
 416,
 384,
 440,
 779,
 240,
 834,
 572,
 264,
 281,
 431,
 702,
 486,
 577,
 578,
 480,
 567,
 460,
 420,
 832,
 628,
 326,
 576,
 551,
 205,
 308,
 336,
 530,
 765,
 528,
 666,
 672,
 606,
 0,
 739,
 550,
 400,
 408,
 0,
 384,
 472,
 576,
 475,
 478,
 704,
 439,
 983,
 300,
 564,
 420,
 463,
 548,
 768,
 660,
 540,
 632,
 888,
 539,
 608,
 438,
 541,
 264,
 300,
 320,
 400,
 800,
 0,
 572,
 360,
 288,
 539,
 480,
 462,
 831,
 554,
 864,
 527,
 240,
 0,
 400,
 576,
 878,
 440,
 440,
 578,
 440,
 440,
 752,
 300,
 440,
 614,
 856,
 481,
 592,
 496,
 423,
 484,
 841,
 576,
 396,
 672,
 275,
 895,
 412,
 865,
 440,
 630,
 504,
 402,
 484,
 605,
 602,
 0,
 457,
 416,
 618,
 281,
 444,
 397,
 539,
 455,
 474,
 409,
 476,
 528,
 240,
 820,
 240,
 603,
 440,
 410,
 1020,
 286,
 554,
 384,
 528,
 484,
 360,
 484,
 420,
 504,
 301,
 280,
 598,
 275,
 857,
 440,
 484,
 595,
 576,
 433,
 240,
 776,
 1220,
 0,
 527,
 538,
 480,
 458,
 480,
 613,
 472,
 456,
 436,
 812,
 264,
 352,
 240,
 400,
 686,
 490,
 0,
 720,
 611,
 425,
 338,
 360,
 512,
 420,
 400,
 240,
 645,
 454,
 260,
 576,
 343,
 479,
 619,
 216,
 504,
 480,
 672,
 529,
 902,
 870,
 544,
 672,
 574,
 308,
 523,
 414,
 288,
 200,
 550,
 648,
 738,
 576,
 336,
 450,
 400,
 389,
 440,
 288,
 506,
 588,
 300,
 621,
 505,
 576,
 440,
 264,
 354,
 400,
 483,
 327,
 528,
 820,
 288,
 684,
 756,
 393,
 690,
 288,
 280,
 865,
 180,
 484,
 390,
 480,
 252,
 450,
 871,
 528,
 286,
 308,
 284,
 833,
 601,
 471,
 0,
 397,
 533,
 612,
 540,
 656,
 486,
 522,
 642,
 610,
 429,
 788,
 570,
 505,
 528,
 555,
 689,
 868,
 349,
 574,
 390,
 0,
 576,
 525,
 456,
 796,
 808,
 474,
 676,
 720,
 300,
 396,
 530,
 0,
 492,
 462,
 576,
 531,
 484,
 0,
 619,
 440,
 702,
 510,
 393,
 256,
 260,
 0,
 264,
 0,
 474,
 264,
 480,
 532,
 490,
 0,
 569,
 400,
 480,
 588,
 676,
 388,
 779,
 539,
 240,
 255,
 606,
 551,
 614,
 870,
 424,
 440,
 564,
 786,
 305,
 368,
 615,
 210,
 632,
 ...]

In [21]:
house_p["GarageCond"].tolist()

['TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'Gd',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Gd',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'Po',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Ex',
 'Gd',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'Po',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Po',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'Fa',
 'TA',
 nan,
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Po',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 nan,
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'Po',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'Gd',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Ex',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Po',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Gd',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Gd',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 nan,
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'TA',
 'Fa',
 'TA',
 ...]

In [22]:
(house_p["GarageQual"].values == house_p["GarageCond"].values).all()

False

In [ ]:
house_p[["GarageType", "GarageYrBlt", "GarageFinish", "GarageCars", "GarageArea", "GarageQual", "GarageCond"]]